# Site settings
title: From One Science to Another
header-img: img/home-bg.png
email: helendu.614@gmail.com
copyright_name: helenndoo
description: > # this means to ignore newlines until "baseurl:"
  Journey of a PeeWee Developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  helenndoo
learn_profile: helenndoo
email_username: helendu.614@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
